# Generated by Django 2.1.3 on 2018-11-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20181108_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(upload_to='upload/student'),
        ),
    ]
