# Generated by Django 2.1.3 on 2018-11-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20181108_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
