# Generated by Django 2.1.3 on 2018-11-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181108_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(upload_to='student_images'),
        ),
    ]
