# Generated by Django 2.1.3 on 2018-11-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryexit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryexit',
            name='building',
        ),
    ]
