# Generated by Django 2.1.3 on 2018-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryexit', '0003_auto_20181110_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryexit',
            name='id',
        ),
        migrations.AddField(
            model_name='entryexit',
            name='id_name',
            field=models.CharField(default='1601CS53', max_length=8),
        ),
    ]
