# Generated by Django 2.1.3 on 2018-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryexit', '0004_auto_20181110_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexit',
            name='building_name',
            field=models.CharField(default='Hostel', max_length=50),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='id_name',
            field=models.CharField(max_length=8),
        ),
    ]
