# Generated by Django 2.1.3 on 2018-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryexit', '0005_auto_20181110_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexit',
            name='building_name',
            field=models.CharField(max_length=50),
        ),
    ]
